version: '3'
services:
  divercult:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    volumes:
      - ../Divercult/:/workspace:cached
    command: sleep infinity
    links:
      - mysql
  remar:
    build: 
      context: ../remar/
      dockerfile: Dockerfile
    environment: 
      - MONGODB_USER=root
      - MONGODB_PASS=root
      - MONGODB_DATABASE=remar-propeller
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    restart: always
    ports:
      - 80:8080
      - 8009:8009
    volumes:
        - remar-tomcat:/usr/local/tomcat/webapps
        - remar-electron:/root/.electron
    links:
      - mongodb
      - mysql
    tty: true
  mysql:
    build: 
      context: ../mysql
      dockerfile: Dockerfile
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    volumes: 
      - mysql-data:/var/lib/mysql
    restart: always
    command: mysqld --init-file="/init/db_startup.sql" --max-connections=500
  mongodb:
    image: mongo:3.2
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - STORAGE_ENGINE=mmapv1
      - TZ=America/Sao_Paulo
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
volumes: 
  mongo-data:
  mysql-data:
  remar-tomcat:
  remar-electron: